version: "3.8"
services:
  npm:
    container_name: nginx-proxy-manager
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8888:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - npm
networks:
  npm:
    external: true
